[env:tab5_arduino]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
framework = arduino
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
upload_speed = 460800
monitor_speed = 115200
build_type = debug
build_unflags =
    -march=rv32imc
extra_scripts = pre:extra_scripts/force_riscv_toolchain.py
build_flags =
    -march=rv32imafc_zicsr_zifencei
    -mabi=ilp32f
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DLVGL_SYNTH_EMBEDDED
    -Isrc
    -Iui
lib_deps =
    https://github.com/M5Stack/M5Unified.git
    https://github.com/M5Stack/M5GFX.git
    lvgl/lvgl@9.2.2

